name: Sync to A-Team-VPL

on:
  push:
    branches:
      - master

jobs:
  init-first-commit:
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4
      - run: | 
          git config --global user.email "arc-runner-set@texcorver.com"
          git config --global user.name "GitHub Actions"

      - name: Add VPL remote
        run: |
          git remote add VPL git@github.com:A-Team-VPL/utils.git
      
      - name: Init first commit
        run: |
          if git ls-remote --exit-code VPL; then
            echo "Repository has content. Proceeding with normal sync."
          else
            echo "Repository is empty. Initializing it."
            git checkout --orphan temp-branch
            git reset --hard # Ensure that the branch is empty
            git commit --allow-empty -m "Initial commit"
            git push VPL temp-branch:master
          fi
  sync:
    needs: init-first-commit
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - run: | 
        git config --global user.email "arc-runner-set@texcorver.com"
        git config --global user.name "GitHub Actions"
      - name: Push to A-Team-VPL/sync
        run: |
          git remote add VPL git@github.com:A-Team-VPL/utils.git
          git fetch VPL
          git merge VPL/master --no-edit --allow-unrelated-histories 
          git push VPL master:sync

  merge-and-delete-sync:
    runs-on: ubuntu-latest
    needs: sync

    steps:
      - uses: actions/checkout@v4
        with:
          repository: A-Team-VPL/utils
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: master

      - run: | 
          git config --global user.email "arc-runner-set@texcorver.com"
          git config --global user.name "GitHub Actions"

      - name: Merge sync to master
        run: |
          git fetch origin sync
          git checkout master
          git merge origin/sync --no-edit --allow-unrelated-histories

      - uses: ad-m/github-push-action@master
        with:
          repository: A-Team-VPL/utils
          branch: master
          ssh: true

      - name: Delete the sync branch
        run: |
          git push origin --delete sync
