name: Sync to A-Team-VPL

on:
  push:
    branches:
      - master

jobs:
  sync: 
    runs-on: arc-runner-set

    steps:
      - uses: actions/checkout@v4
      - name: Sync to A-Team-VPL
        run: |
          git remote add VPL git@github.com:A-Team-VPL/utils.git
          git push VPL master:sync
      
      - uses: actions/checkout@v4
        with:
          repository: A-Team-VPL/utils
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: master

      - name: Merge from A-Team-VPL/sync to A-Team-VPL/master
        run: |
          # Ensure that the sync branch is not conflicting with the master branch
          git merge sync --no-edit

      - uses: ad-m/github-push-action@master
        with:
          repository: A-Team-VPL/utils
          branch: master
          ssh: true