name: Sync to A-Team-VPL

on:
  push:
    branches:
      - master

jobs:
  init-first-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: A-Team-VPL/utils
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: master
      - name: Create sync branch
        run: |
          if git ls-remote --exit-code origin; then
            echo "Repository has content. Proceeding with normal sync."
          else
            echo "Repository is empty. Initializing it."
            git checkout -b master
            git config user.name "GitHub Actions"
            git commit --allow-empty -m "Initial commit"
            git push origin master
          fi

  sync:
    runs-on: arc-runner-set
    needs: init-first-commit

    steps:
      - uses: actions/checkout@v4
      - name: Sync to A-Team-VPL
        run: |
          git remote add VPL git@github.com:A-Team-VPL/utils.git
          git push VPL master:sync
  
  merge:
    runs-on: ubuntu-latest
    needs: sync

    steps:
      - uses: actions/checkout@v4
        with:
          repository: A-Team-VPL/utils
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: master

      # Step 4: Merge sync into master in A-Team-VPL/utils
      - name: Merge sync to master
        run: |
          git fetch origin sync
          git checkout master
          # Ensure that the sync branch is not conflicting with the master branch
          git merge sync --no-edit

      - uses: ad-m/github-push-action@master
        with:
          repository: A-Team-VPL/utils
          branch: master
          ssh: true

      - name: Delete the sync branch
        run: |
          git push origin --delete sync
