name: unit-test
on: 
    push:
        branches: [master, dev, NEXT*]
    pull_request:
        branches: [master, dev]
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: '3.12.2'
            - run: python -m pip install --upgrade pip
            - run: python -m pip install poetry==1.7
            - run: poetry install
            - run: poetry run pytest tests/unit
